___
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
a = np.ones(10)
a *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
b = np.arange(10,51)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(11,51,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.array(([0,1,2],[3,4,5],[6,7,8]))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
c = np.arange(0,9)
d=c.reshape(3,3)

In [10]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand(1)

array([0.93331965])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [13]:
np.random.randn(25)

array([-0.08040591,  0.03451585, -0.2812551 ,  0.88696291, -0.56874192,
       -2.07482133,  1.14751509, -0.86879199,  0.02347367, -0.4521296 ,
        0.27261002, -0.71900505, -1.50111329, -1.1401352 , -2.14277439,
       -0.10245515,  0.42576942,  0.52368375,  0.48904485, -0.14307168,
       -0.67349022, -0.51298097,  0.9378873 ,  0.16619262,  1.61445033])

In [14]:
np.random.normal(0,1,25)

array([-0.0041603 , -1.00483009, -0.39515109,  0.34170066,  1.03724937,
        1.00891146, -1.26996369, -0.73287114,  1.35026559,  0.82155647,
        0.3557318 , -1.33218357,  0.77148722,  0.42524079, -0.76011505,
        1.40109937, -3.21395438, -0.43435529,  0.37311015,  0.75213409,
       -0.53063634,  0.05008646,  2.26872055, -1.18192986, -1.15193438])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [28]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
mat[1:2,3:]

array([[ 9, 10]])

In [17]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [18]:
mat[3,4]

20

In [19]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
print(mat[0,1])
print(mat[1,1])
print(mat[2,1])

2
7
12


In [21]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [22]:
mat[4]

array([21, 22, 23, 24, 25])

In [23]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [24]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [25]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [26]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [27]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!